server-port=25565
server-ip=
motd=Ashraf Paper Server
online-mode=false
max-players=10
difficulty=normal
gamemode=survival
spawn-protection=0
allow-flight=false
view-distance=8
simulation-distance=6
enforce-secure-profile=false
white-list=false
